dist: bionic

language: ruby
rvm:
 - 2.6.6
cache: bundler

before_install:
  - sudo apt-get update
  - sudo apt-get -y install graphviz
  - >
    export APPLAND_CLI_DOWNLOAD_URL="$(curl -s https://api.github.com/repos/applandinc/appland-cli/releases/latest \
      | jq -r '.assets[] | select(.name | contains("Linux")).browser_download_url')" \
      && curl -sSL "${APPLAND_CLI_DOWNLOAD_URL}" \
      | sudo tar xz --directory /usr/local/bin appland \
      && touch ~/.appland
  - nvm install 12.18.1

script:
  - yarn
  - bundle exec rake db:migrate
  - env APPMAP=true bundle exec rake test
  - yarn scanner --config=../sampleConfig/railsSampleApp6thEd.js --commit-status=github --appmap-dir=tmp/appmap

after_success:
- env DEBUG=true ./bin/upload-appmaps
