on: [push]
name: Install AppMap
jobs:
  install_appmap_job:
    runs-on: ubuntu-latest
    name: Install AppMap
    steps:
      - name: Checkout step
        uses: actions/checkout@v3
      - name: Install AppMap step
        uses: getappmap/install-appmap-action@v1-pre.1
        id: install-appmap
      - name: Commit changes
        uses: EndBug/add-and-commit@v9
